name: Publish container image

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
    
    steps:
      - name: Aquire code
        if: always()
        uses: actions/checkout@v2
      - name: Log into ghcr.io
        uses: docker/login-action@v2
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/mini-bomba/create-github-release
          tags: |
            type=ref,event=branch
            type=semver,pattern={{raw}}
            type=sha,prefix=,suffix=,format=short
      - name: Build & push image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
